AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CodeCommitRepo:
    Type: 'AWS::CodeCommit::Repository'
    Properties:
      RepositoryName: portfolio-web-app
      RepositoryDescription: Main repository for the web application
