AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AmiId: {Type: String}
Resources:
  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AmiId
      InstanceType: t3.micro
      Tags:
        - {Key: Name, Value: WebServer01}
        - {Key: Environment, Value: Dev}
